<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class Post extends Model
{
    use HasFactory;

    protected static function booted()
    {
//        parent::booted(); // TODO: Change the autogenerated stub
        static::addGlobalScope('ordered', function (Builder $builder) {
            $builder->orderBy('created_at', 'DESC');
        });
    }


    protected $withCount = ['likes'];

    protected $fillable = [
        'text', 'image',
    ];


    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function likes()
    {
        return $this->morphToMany(Like::class, 'likeable', 'likeable');
    }

}
